### ISSUE TITLE
if pets disable players can see the pets

### ISSUE THREAD

**Issue by Driesboy** [Driesboy/Pets#1]

**Comment by remotevase** [comment]
Whose plugin was this originally? Give credit

**Comment by Driesboy** [comment]
See in plugin.yml
Op 5-jun.-2016 14:59 schreef "remote_vase" <notifications@github.com>:

**Comment by remotevase** [comment]
There is no plugin.yml

**Comment by Driesboy** [comment]
i forgot it 📦

**Comment by remotevase** [comment]
I made it

**Comment by Driesboy** [comment]
ok lifeboat

**Comment by Driesboy** [comment]
is original author

**Comment by remotevase** [comment]
I know, which means that this plugin was **stolen** from the hacked lifeboat's core

**Comment by Driesboy** [comment]
yes

**Comment by remotevase** [comment]
therefore, i will delete this, as it is not fully legal. first, though, transfer it to ur account if ya want. I will give you 60 minutes until i delete this

**Comment by Taki21** [comment]
well lifeboat posts several things SOMETIMES...

**Comment by remotevase** [comment]
Hmmm, I don't think this is one of them, is it?
