### ISSUE TITLE
Please add permissions

### ISSUE THREAD

**Issue by iMOEchan** [Driesboy/Pets#2]
So VIP player can do /pets

**Comment by Driesboy** [comment]
there are permissions pets.command!

**Comment by iMOEchan** [comment]
Really ?

Image : http://i.hizliresim.com/1dMl7A.jpg

**Comment by HyGlobalHD** [comment]
There Have See This There Pets.Command

https://github.com/Driesboy/Pets/blob/master/src/pets/PetCommand.php
