### ISSUE TITLE
Multiple Pets

### ISSUE THREAD

**Issue by linuzo** [Driesboy/Pets#3]
If players will do /pets type pet then the pets will not go away they will just keep coming and adding more pets... 

https://images-2.discordapp.net/.eJwFwcl2gjAUANB_Yc_QBD3gLlaDDTWtRUTdeCgyhKE8CTKkp__ee3-1Z1drK63oe5Ar0xRNnKdSR8ZdyKTt7jGA8ZP2ppGykQsq_XEmB_JxE4N-OyE6l-u5ELR6YbLy8Hl5wp0i-xErCpMr6AUvdo8hQsr23dDiAHb3qCDcOAp_1kERoqw58wejo9tvscjIm8_2k32ou-Y1CBZUbrwr-84v7ju3Jk9aNiSKV-0R2BNZkm-HSJf2kOwKErbRaGTTdUBHuV6WOYnyyJncGb5iJR2vMkpIc-3vH-7qUUc.dMZrHGQh9uDhm_zUdKIXre27KPI.jpeg

**Comment by Driesboy** [comment]
fixed
