### ISSUE TITLE
Some code...

### ISSUE THREAD

**Issue by GlitchPlayer** [Driesboy/Pets#7]
Some code in here are from LostTeam.
Please provide credits then.

**Comment by Driesboy** [comment]
not!
its not from LostTeam!

**Comment by HyGlobalHD** [comment]
@GlitchPlayer how you know there LostTeam code? any evidence?

**Comment by GlitchPlayer** [comment]
Check our repo
www.github.com/LostTeam/LostPets

**Comment by remotevase** [comment]
@GlitchPlayer Both LostTeam and Driesboy took the original code basis from Lifeboat core.
