### ISSUE TITLE
ParseError: "syntax error, unexpected '$sender' (T_VARIABLE)" 

### ISSUE THREAD

**Issue by Driesboy** [Driesboy/Pets#7]
[Server thread/CRITICAL]: ParseError: "syntax error, unexpected '$sender' (T_VARIABLE)" (EXCEPTION) in "/plugins/Pets-master/src/pets/command/PetCommand" at line 94

**Comment by linuzo** [comment]
if($this->getConfig()->get("Dog") === true){
								$this->main->changePet($sender, "WolfPet");
								$pettype = "Dog"
								$sender->sendMessage($this->getConfig()->get("PetCreateMessage"));
							}

Change 
$pettype = "Dog"
to 
$pettype = "Dog";

**Comment by Driesboy** [comment]
ok its stupid
