### ISSUE TITLE
It doesnt work

### ISSUE THREAD

**Issue by xKenn12** [Driesboy/Pets#8]
Hello the config is not showing up and when i try /plugins on my server the pets is on the red letter

Sorry for bad english

**Comment by HyGlobalHD** [comment]
Download the plugin at the readme.MD
the (.phar)

**Comment by xKenn12** [comment]
Is there a permission nodes for pets? I want to put it to all players

**Comment by remotevase** [comment]
@xKenn12 no, there are no official permissions. You can always check for permissions by looking in the plugin.yml file!

**Comment by HyGlobalHD** [comment]
The permission is pets.command

it shown at PetCommand.php
https://github.com/Driesboy/Pets/blob/master/src/pets/PetCommand.php

**Comment by xKenn12** [comment]
Oh Okay
